apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: train-schedule
  name: train-schedule-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        name: train-schedule
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: train-schedule
  name: train-schedule-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30088
  selector:
    app: train-schedule
  sessionAffinity: None
  type: NodePort
